# https://taskfile.dev

version: '3'

dotenv: ['.env', '{{.ENV}}/.env', '{{.HOME}}/.env']

tasks:
  setup:
    cmds:
      - go mod tidy

  test:
    cmds:
      - go test -v -failfast -race -coverpkg=./... -covermode=atomic -coverprofile=coverage.txt ./...

  lint:
    cmds:
      - golangci-lint run

  build:
    cmds:
      - go build -o ./dist/how ./cmd/how

  dev:
    cmds:
      - go run ./cmd/how
